version: "2"
run:
  tests: true
  timeout: 5m
linters:
  enable:
    - dogsled
    - goconst
    - gocritic
    - gosec
    - ineffassign
    - misspell
    - nakedret
    # - staticcheck
    - revive
    - unconvert
    - unused
  settings:
    dogsled:
      max-blank-identifiers: 3
    nolintlint:
      allow-unused: false
      require-explanation: false
      require-specific: false
    revive:
      rules:
        - name: unused-parameter
          disabled: true

issues:
  max-issues-per-linter: 10000
  max-same-issues: 10000

